name: snapgoals_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  sqflite: ^2.0.0+3
  sqflite_common_ffi: ^2.3.2
  path_provider: ^2.1.2
  charts_flutter: any
  provider: ^6.1.1
  shared_preferences: ^2.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
